name: Deploy to production stand

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        description: "tag to deploy from"
        default: ""
        required: false
        type: string
  push:
    branches:
      - "!*"
    tags:
      - "*"

jobs:
  Deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default
        if: ${{ inputs.tag == "" }}
        uses: actions/checkout@v3
      
      - name: Checkout tag
        if: ${{ inputs.tag != "" }}
        uses: actions/checkout@v3
        with:
          ref: refs/tags/${{ inputs.tag }}

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      
      - run: npm ci

      - run: npm run build --if-present

      - name: Copy build files to host
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.BEGET_HOST }}
          username: ${{ secrets.BEGET_USER }}
          password: ${{ secrets.BEGET_PASSWORD }}
          source: "build/*"
          target: ${{ secrets.PROD_URL}}/public_html
          rm: true
          strip_components: 1
